// Built-in CSV layouts for UK banks and platforms. These are data, in the same shape as the profiles
// you save yourself (data/csv-profiles.json), and are matched by header signature. To support a new
// bank, add an entry here (and a fixture + test in tests/csv.test.ts), or just map its columns once
// in the Import screen and save the mapping.

import type { CsvProfile } from '../../shared/schema';

const P = (p: Omit<CsvProfile, 'builtin' | 'dateOrder' | 'amountSign'> & Partial<Pick<CsvProfile, 'dateOrder' | 'amountSign'>>): CsvProfile => ({
  dateOrder: 'DMY',
  amountSign: 'normal',
  builtin: true,
  ...p,
});

export const BUILTIN_CSV_PROFILES: CsvProfile[] = [
  P({
    id: 'monzo',
    name: 'Monzo',
    institutionId: 'monzo',
    accountType: 'current',
    headerSignature: ['transaction id', 'date', 'time', 'type', 'name', 'amount', 'currency', 'local amount'],
    columns: {
      id: 'Transaction ID',
      date: 'Date',
      time: 'Time',
      type: 'Type',
      description: ['Description'],
      payee: 'Name',
      category: 'Category',
      amount: 'Amount',
      currency: 'Currency',
      localAmount: 'Local amount',
      localCurrency: 'Local currency',
      merchantAddress: 'Address',
    },
  }),
  P({
    id: 'starling',
    name: 'Starling',
    institutionId: 'starling',
    accountType: 'current',
    headerSignature: ['date', 'counter party', 'reference', 'type', 'amount (gbp)', 'balance (gbp)'],
    columns: {
      date: 'Date',
      description: ['Counter Party', 'Reference'],
      counterparty: 'Counter Party',
      reference: 'Reference',
      type: 'Type',
      amount: 'Amount (GBP)',
      balance: 'Balance (GBP)',
      category: 'Spending Category',
    },
  }),
  P({
    id: 'revolut',
    name: 'Revolut',
    institutionId: 'revolut',
    accountType: 'current',
    dateOrder: 'YMD',
    headerSignature: ['type', 'product', 'started date', 'completed date', 'description', 'amount', 'fee', 'currency', 'state', 'balance'],
    columns: {
      date: 'Completed Date',
      time: 'Completed Date',
      transactionDate: 'Started Date',
      type: 'Type',
      description: ['Description'],
      amount: 'Amount',
      fee: 'Fee',
      currency: 'Currency',
      balance: 'Balance',
    },
    filter: { column: 'State', values: ['COMPLETED'] },
    splitBy: ['Product', 'Currency'],
  }),
  P({
    id: 'barclays',
    name: 'Barclays',
    institutionId: 'barclays',
    accountType: 'current',
    headerSignature: ['number', 'date', 'account', 'amount', 'subcategory', 'memo'],
    columns: {
      date: 'Date',
      description: ['Memo'],
      type: 'Subcategory',
      amount: 'Amount',
      accountNumber: 'Account',
    },
  }),
  P({
    id: 'chase',
    name: 'Chase UK',
    institutionId: 'chase',
    accountType: 'current',
    headerSignature: ['date', 'time', 'transaction type', 'transaction description', 'amount', 'currency', 'balance'],
    columns: {
      date: 'Date',
      time: 'Time',
      type: 'Transaction Type',
      description: ['Transaction Description'],
      amount: 'Amount',
      currency: 'Currency',
      balance: 'Balance',
    },
  }),
  P({
    id: 'lloyds-group',
    name: 'Lloyds / Halifax / Bank of Scotland / TSB',
    accountType: 'current',
    headerSignature: ['transaction date', 'transaction type', 'sort code', 'account number', 'transaction description', 'debit amount', 'credit amount', 'balance'],
    columns: {
      date: 'Transaction Date',
      type: 'Transaction Type',
      description: ['Transaction Description'],
      debit: 'Debit Amount',
      credit: 'Credit Amount',
      balance: 'Balance',
      accountNumber: 'Account Number',
    },
  }),
  P({
    id: 'natwest-group',
    name: 'NatWest / RBS / Ulster',
    accountType: 'current',
    headerSignature: ['date', 'type', 'description', 'value', 'balance', 'account name', 'account number'],
    columns: {
      date: 'Date',
      type: 'Type',
      description: ['Description'],
      amount: 'Value',
      balance: 'Balance',
      accountNumber: 'Account Number',
    },
  }),
  P({
    id: 'nationwide-current',
    name: 'Nationwide (current account)',
    institutionId: 'nationwide',
    accountType: 'current',
    headerSignature: ['date', 'transaction type', 'description', 'paid out', 'paid in', 'balance'],
    columns: {
      date: 'Date',
      type: 'Transaction type',
      description: ['Description'],
      debit: 'Paid out',
      credit: 'Paid in',
      balance: 'Balance',
    },
  }),
  P({
    id: 'nationwide-credit-card',
    name: 'Nationwide (credit card)',
    institutionId: 'nationwide',
    accountType: 'credit_card',
    headerSignature: ['date', 'transactions', 'location', 'paid out', 'paid in'],
    columns: {
      date: 'Date',
      description: ['Transactions'],
      merchantCity: 'Location',
      debit: 'Paid out',
      credit: 'Paid in',
    },
  }),
  P({
    id: 'amex',
    name: 'American Express',
    institutionId: 'amex',
    accountType: 'credit_card',
    amountSign: 'inverted',
    headerSignature: ['date', 'description', 'amount', 'appears on your statement as', 'reference'],
    columns: {
      date: 'Date',
      description: ['Description'],
      amount: 'Amount',
      id: 'Reference',
      reference: 'Appears On Your Statement As',
      category: 'Category',
      merchantAddress: 'Address',
      merchantCity: 'Town/City',
      merchantPostcode: 'Postcode',
      merchantCountry: 'Country',
    },
  }),
  P({
    id: 'trading-212',
    name: 'Trading 212',
    institutionId: 'trading-212',
    accountType: 'stocks_isa',
    dateOrder: 'YMD',
    headerSignature: ['action', 'time', 'isin', 'ticker', 'name', 'total'],
    columns: {
      date: 'Time',
      time: 'Time',
      type: 'Action',
      description: ['Action', 'Name', 'Notes'],
      amount: 'Total',
      currency: 'Currency (Total)',
      id: 'ID',
    },
    negativeWhen: { column: 'Action', values: ['Market buy', 'Limit buy', 'Stop buy', 'Stop limit buy', 'Withdrawal', 'Currency conversion fee', 'Card debit'] },
  }),
  P({
    id: 'hsbc',
    name: 'HSBC (no header row)',
    institutionId: 'hsbc',
    accountType: 'current',
    headerSignature: ['date', 'description', 'amount'],
    headerless: ['Date', 'Description', 'Amount'],
    columns: { date: 'Date', description: ['Description'], amount: 'Amount' },
  }),
  P({
    id: 'date-description-amount',
    name: 'Date / Description / Amount (first direct and others)',
    headerSignature: ['date', 'description', 'amount'],
    columns: { date: 'Date', description: ['Description'], amount: 'Amount' },
  }),
];
